#! /bin/sh

# █▄▄ █▀ █▀█ █░█░█ █▀▄▀█
# █▄█ ▄█ █▀▀ ▀▄▀▄▀ █░▀░█

#bspc monitor -d I II III IV V VI
bspc monitor -d I II III IV

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    6
bspc config top_padding                   29
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config -d '^4' window_gap 36
bspc config -d '^3' window_gap 10

#### BSPWM coloring ####
#bspc config normal_border_color   "#131520"
#bspc config normal_border_color   "#2e3440"
#bspc config active_border_color   "#ffffff"
#bspc config focused_border_color  "#d8dee9"
#bspc config presel_feedback_color "#eceff4"
#bspc config urgent_border_color   "#bf616a"

#### BSPWM Dracula color scheme ####
bspc config normal_border_color   "#1b1b1b"
bspc config active_border_color   "#1b1b1b"
bspc config focused_border_color  "#6272a4"
bspc config presel_feedback_color "#44475a"

#### BSPWM Window rules ####
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mpv desktop='^4' follow=on
#bspc rule -a Alacritty state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Popsicle state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xfce4-panel state=floating
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a "Tor Browser" state=floating border=off
bspc rule -a Gufw.py state=floating
bspc rule -a Lxterminal state=floating
bspc rule -a Panther_launcher state=floating
bspc rule -a Peek state=floating
bspc rule -a Xfce4-settings-manager state=floating
bspc rule -a URxvt state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Software-properties-gtk state=floating
bspc rule -a fragments state=floating

bspc rule -a Brave-browser border=off
bspc rule -a Chromium border=off


#######Auto-start#################
sxhkd &
sh ~/.config/bspwm/autostart.sh &
