;█▀█ █▀█ █░░ █▄█ █▄▄ ▄▀█ █▀█ ThunderThief
;█▀▀ █▄█ █▄▄ ░█░ █▄█ █▀█ █▀▄ vim:fileencoding=utf-8:foldmethod=marker:ft=dosini

[bar/bspbar]

;------------;
; DIMENSIONS ;
;------------;

width = 100%
height = 29
offset-y = 0
offset-x = 0%

radius = 3px

border-top-size    = 0
border-bottom-size = 1
border-right-size  = 5
border-left-size   = 5

;----------;
; LOCATION ;
;----------;

bottom            = true
monitor           = LVDS-1
wm-restack        = bspwm
override-redirect = true

;-------;
; FONTS ;
;-------;

font-0 = "Product Sans:style=Bold:pixelsize=11;2"
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=11;2"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=11;2"
font-3 = "Font Awesome 5 Duotone:style=Solid:pixelsize=11;2"
font-4 = "Font Awesome 5 Brands:pixelsize=11;2"
font-5 = "Font Awesome 5 Pro:style=Regular:pixelsize=11;2"
font-6 = "Font Awesome 5 Pro:style=Solid:pixelsize=11;2"
font-7 = "Font Awesome 5 Pro:style=Light:pixelsize=11;2"

;--------;
; COLORS ;
;--------;

background    = ${colors.bg}
foreground    = ${colors.fg}
;border-color = 0

;---------------;
; MISCELLANEOUS ;
;---------------;

fixed-center  = true
padding-left  = 5
padding-right = 5
module-margin = 2

modules-left   = bspwm
modules-center = xwindow
modules-right  = xkeyboard volume backlight wlan battery0 battery1 time powerbutton

tray-position = none
tray-detached = flase
tray-padding  = 1


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;---------------;
; MODULES File  ;
;---------------;

include-file = ~/.config/polybar/modules.conf
