#!/usr/bin/env bash

overlay=~/.config/blurlock/lockoverlay.png

#scrot /tmp/currentworkspace.png
convert /home/thunderthief/.config/blurlock/14.png  -blur 0x5 /tmp/currentworkspaceblur.png
composite -gravity southeast $overlay /tmp/currentworkspaceblur.png /tmp/lockbackground.png
i3lock -i /tmp/lockbackground.png
