;█▀█ █▀█ █░░ █▄█ █▄▄ ▄▀█ █▀█ ThunderThief
;█▀▀ █▄█ █▄▄ ░█░ █▄█ █▀█ █▀▄ vim:fileencoding=utf-8:foldmethod=marker:ft=dosini


[bar/i3bar]

;------------;
; DIMENSIONS ;
;------------;

width = 100%
height = 29
offset-y = 0
offset-x = 0

radius = 3px

border-top-size    = 1
border-bottom-size = 0
border-right-size  = 5
border-left-size   = 5

;----------;
; LOCATION ;
;----------;

bottom            = false
monitor           = LVDS-1
;wm-restack       = none
override-redirect = false

;-------;
; FONTS ;
;-------;

font-0 = "Product Sans:style=Bold:pixelsize=11;2"
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=11;2"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=11;2"
font-3 = "Font Awesome 5 Duotone:style=Solid:pixelsize=11;2"
font-4 = "Font Awesome 5 Brands:pixelsize=11;2"
font-5 = "Font Awesome 5 Pro:style=Regular:pixelsize=11;2"
font-6 = "Font Awesome 5 Pro:style=Solid:pixelsize=11;2"
font-7 = "Font Awesome 5 Pro:style=Light:pixelsize=11;2"

;--------;
; COLORS ;
;--------;


background    = ${colors.bg}
foreground    = ${colors.fg}
;border-color = 0

;---------------;
; MISCELLANEOUS ;
;---------------;

fixed-center   = true
padding-left   = 5
padding-right  = 5
module-margin  = 2

modules-left   = xwindow
modules-center = i3
modules-right  = sep1 xkeyboard volumebar time wlan battery0 battery1 powerbutton sep2

tray-position  = none
tray-detached  = false
tray-padding  = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;---------------;
; MODULES File  ;
;---------------;

include-file = ~/.config/polybar/modules.conf
